image_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('views/', include('views.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

views/urls.py
from django.urls import path

from . import views

app_name = 'views'
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path('submit/', views.submit, name='submit'),
    path('update/<int:pk>/', views.update, name='update'),
    path('show/<int:pk>/', views.ShowView.as_view(), name='show'),
    path('search/', views.search, name='search'),
    path('skim/', views.keywords, name='skim'),
]

views/models.py
import datetime, os

from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils import timezone

file_storage = FileSystemStorage()

class Image(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    keywords = models.CharField(max_length=200)
    image = models.FileField(storage=file_storage)
    pub_date = models.DateTimeField('date published')

    @property
    def filename(self):
        return os.path.basename(self.image.name)

class Keyword(models.Model):
    keyword = models.CharField(max_length=200)
    uses = models.IntegerField(default=0)

    def __str__(self):
        return self.keyword

views/admin.py
from django.contrib import admin

from .models import Image, Keyword

admin.site.register(Image)
admin.site.register(Keyword)

views/apps.py
from django.apps import AppConfig


class ViewsConfig(AppConfig):
    name = 'views'

views/tests.py
from django.test import TestCase

# Create your tests here.

views/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.views import generic
from django.db.models import Q
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required

from .models import Image, Keyword


class IndexView(generic.ListView):
    template_name = 'views/index.html'
    context_object_name = 'latest_images'

    def get_queryset(self):
        page = self.request.GET.get('page', 0)
        limit = self.request.GET.get('limit', 25)
        page = int(page)
        limit = int(limit)
        start = page * limit
        end = (page + 1) * limit
        if start < 0:
            start = 0
            end = limit
        return Image.objects.order_by('-pub_date')[start:end]

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', 0)
        page = int(page)
        ctx['last_page'] = page - 1
        ctx['page'] = page
        ctx['next_page'] = page + 1
        ctx['limit'] = self.request.GET.get('limit', 25)
        return ctx


@login_required
def submit(request):
    if request.method == "POST":
        try:
            image_image = request.FILES["image_image"]
            image_title = request.POST["image_title"]
            image_description = request.POST["image_description"]
            image_keywords = request.POST["image_keywords"]
            pub_date = timezone.now()
        except KeyError as ke:
            print("Key error({0})".format(ke))
            print(request.POST)
            return render(request, 'views/submit.html', {
                'error_message': "Information missing.",
            })
        image = Image(
            title=image_title,
            description=image_description,
            keywords=image_keywords,
            pub_date=pub_date)

        splits = image_image.name.split(".")
        filetype = splits[len(splits)-1:]
        image_image.name = "{0}.{1}".format(str(image.id), filetype)
        image.image = image_image
        image.save()

        for key in image_keywords.split(","):
            new_key, created = Keyword.objects.get_or_create(keyword=key.strip().lower())
            new_key.uses += 1
            new_key.save()

        return HttpResponseRedirect(reverse('views:show', args=(image.id,)))
    else:
        suggestions = []
        for word in Keyword.objects.all():
            suggestions.append(word.keyword)
        suggestions.sort()
        context = {
            "suggested_keywords": suggestions
        }
        return render(request, 'views/submit.html', context)


@login_required
def update(request, pk):
    if request.method == "POST":
        try:
            image_id = pk
            image_title = request.POST["image_title"]
            image_description = request.POST["image_description"]
            image_keywords = request.POST["image_keywords"]
            pub_date = timezone.now()
        except KeyError as ke:
            print("Key error({0})".format(ke))
            print(request.POST)
            return render(request, 'views/submit.html', {
                'error_message': "Information missing.",
            })
        image = Image.objects.get(id=image_id)
        image.title=image_title
        image.description=image_description
        image.keywords=image_keywords
        image.pub_date=pub_date

        image.save()

        for key in image_keywords.split(","):
            new_key, created = Keyword.objects.get_or_create(keyword=key.strip().lower())
            new_key.uses += 1
            new_key.save()

        return HttpResponseRedirect(reverse('views:show', args=(image.id,)))
    else:
        image = Image.objects.get(id=pk)
        suggestions = []
        for word in Keyword.objects.all():
            suggestions.append(word.keyword)
        suggestions.sort()
        context = {
            "suggested_keywords": suggestions,
            "image": image
        }
        return render(request, 'views/edit.html', context)


class ShowView(generic.DetailView):
    model = Image
    template_name = 'views/show.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        keywords = context['image'].keywords
        context['keywords'] = keywords.split(",")
        return context


def search(request):
    keywords = getValueOr(request.GET, 'keywords', '')
    page = int(getValueOr(request.GET, 'page', '0'))
    limit = int(getValueOr(request.GET, 'limit', '25'))
    page = int(page)
    limit = int(limit)

    suggestions = []
    for word in Keyword.objects.all():
        suggestions.append(word.keyword)
    suggestions.sort()

    if len(keywords) == 0:
        context = {
            "keywords": keywords,
            "page": page,
            "limit": limit,
            "suggested_keywords": suggestions
        }
        return render(request, 'views/search.html', context)
    keys = keywords.split(",")

    # This seems like poor poor database handling to me...
    # But I'm too lazy to fix it right now... so eh?
    images = Image.objects.all()
    for key in keys:
        images = images.filter(Q(keywords__contains=key.strip().lower()))
    start = page*limit
    end = (page+1)*limit
    if start < 0:
        start = 0
        end = limit
    images = images[start:end]

    context = {
        "filtered_images": images,
        "keywords": keywords,
        "page": page,
        "last_page": page-1,
        "next_page": page+1,
        "limit": limit,
        "suggested_keywords": suggestions
    }

    return render(request, 'views/search.html', context)

def keywords(request):
    keywords = Keyword.objects.all().order_by('keyword')
    max_uses = 0
    for keyword in keywords:
        if max_uses < keyword.uses:
            max_uses = keyword.uses

    for keyword in keywords:
        keyword.fontsize = 30 + ((keyword.uses - max_uses) / max_uses) * 16
        if 30 < keyword.fontsize:
            keyword.fontsize = 30

    context = {
        "keywords": keywords
    }
    return render(request, 'views/keywords.html', context)


def getValueOr(dictionary, key, default):
    try:
        return dictionary[key]
    except MultiValueDictKeyError:
        return default

views/templates/views/edit.html
{% load static %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="{% static 'views/style.css' %}">

<script>
    $( function() {
        var availableTags = [
        {% for word in suggested_keywords %}
            "{{ word }}",
        {% endfor %}
        ];
        function split( val ) {
          return val.split( /,\s*/ );
        }
        function extractLast( term ) {
          return split( term ).pop();
        }

        $( "#keywords" )
        // don't navigate away from the field on tab when selecting an item
        .on( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).autocomplete( "instance" ).menu.active ) {
            event.preventDefault();
        }
        })
        .autocomplete({
            minLength: 0,
            source: function( request, response ) {
                // delegate back to autocomplete, but extract the last term
                response( $.ui.autocomplete.filter(
                availableTags, extractLast( request.term ) ) );
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function( event, ui ) {
                var terms = split( this.value );
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push( ui.item.value );
                // add placeholder to get the comma-and-space at the end
                terms.push( "" );
                this.value = terms.join( ", " );
                return false;
            }
        });
    });
</script>

{% include "views/menu.html" %}

<div class="update">
    <h1>Update image</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="image">
        <a href="{{ MEDIA_URL }}{{ image.filename }}">
            <img src="{{ MEDIA_URL }}{{ image.filename }}" />
        </a>
    </div>
    <form autocomplete="off" action="{% url 'views:update' pk=image.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="image_title" placeholder="title" required="true" value="{{ image.title }}" /><br />
        <textarea name="image_description" placeholder="description" rows="3" cols="60" required="true">{{ image.description }}</textarea><br />
        <input type="text" id="keywords" name="image_keywords" placeholder="keywords" required="true" value="{{ image.keywords }}" /><br />
        <input type="submit" value="Update">
    </form>
</div>

<div class="loading hidden"></div>

views/templates/views/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'views/style.css' %}">

{% include "views/menu.html" %}
<div class="mainpage">
    {% if latest_images %}
        <div class="navigation">
            <a href="{% url 'views:index' %}?page={{last_page}}&limit={{limit}}" class="left">&lt;&lt;</a>
            <a href="{% url 'views:index' %}?page={{next_page}}&limit={{limit}}" class="right">&gt;&gt;</a>
        </div>
        {% for image in latest_images %}
            <div class="sample">
                <a href="{% url 'views:show' image.id %}">
                    <div class="title">{{ image.title }}</div>
                    <img src="{{ MEDIA_URL }}{{ image.filename }}" class="sample" />
                </a>
            </div>
        {% endfor %}
        <div class="navigation">
            <a href="{% url 'views:index' %}?page={{last_page}}&limit={{limit}}" class="left">&lt;&lt;</a>
            <a href="{% url 'views:index' %}?page={{next_page}}&limit={{limit}}" class="right">&gt;&gt;</a>
        </div>
    {% else %}
        <p>No images are available.</p>
    {% endif %}
</div>

views/templates/views/keywords.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'views/style.css' %}">

{% include "views/menu.html" %}
<div class="keywords">
    {% for word in keywords %}
        | <a href="{% url 'views:search' %}?keywords={{ word }}" style="font-size:{{ word.fontsize }}px">{{ word.keyword|capfirst }} [{{ word.uses }}]</a>
        {% if forloop.counter|divisibleby:5 %}<br />{% endif %}
    {% endfor %}
</div>

views/templates/views/menu.html
<div class="menu">
<a href="{% url 'views:index' %}">Main Page</a>
<a href="{% url 'views:submit' %}">Submit</a>
<a href="{% url 'views:search' %}">Search</a>
<a href="{% url 'views:skim' %}">Skim</a>
{% if user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}
</div>

views/templates/views/search.html
{% load static %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="{% static 'views/style.css' %}">

<script>
    $( function() {
        var availableTags = [
        {% for word in suggested_keywords %}
            "{{ word }}",
        {% endfor %}
        ];
        function split( val ) {
          return val.split( /,\s*/ );
        }
        function extractLast( term ) {
          return split( term ).pop();
        }

        $( "#keywords" )
        // don't navigate away from the field on tab when selecting an item
        .on( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).autocomplete( "instance" ).menu.active ) {
            event.preventDefault();
        }
        })
        .autocomplete({
            minLength: 0,
            source: function( request, response ) {
                // delegate back to autocomplete, but extract the last term
                response( $.ui.autocomplete.filter(
                availableTags, extractLast( request.term ) ) );
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function( event, ui ) {
                var terms = split( this.value );
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push( ui.item.value );
                // add placeholder to get the comma-and-space at the end
                terms.push( "" );
                this.value = terms.join( ", " );
                return false;
            }
        });
    });
</script>

{% include "views/menu.html" %}

<div class="filter">
    <form autocomplete="off" action="{% url 'views:search' %}" method="get">
        Keywords: <input id="keywords" type="text" name="keywords" value="{{ keywords }}" placeholder="keywords" />
        Page: <input type="number" name="page" value="{{ page }}" />
        Limit: <input type="number" name="limit" value="{{ limit }}" />
        <input type="submit" value="Search">
    </form>
</div>

<div class="mainpage">
    {% if filtered_images %}
        <div class="navigation">
            <a href="{% url 'views:search' %}?keywords={{keywords}}&page={{last_page}}&limit={{limit}}" class="left">&lt;&lt;</a>
            <a href="{% url 'views:search' %}?keywords={{keywords}}&page={{next_page}}&limit={{limit}}" class="right">&gt;&gt;</a>
        </div>
        {% for image in filtered_images %}
            <div class="sample">
                <a href="{% url 'views:show' image.id %}">
                    <div class="title">{{ image.title }}</div>
                    <img src="{{ MEDIA_URL }}{{ image.filename }}" class="sample" />
                </a>
            </div>
        {% endfor %}
        <div class="navigation">
            <a href="{% url 'views:search' %}?keywords={{keywords}}&page={{last_page}}&limit={{limit}}" class="left">&lt;&lt;</a>
            <a href="{% url 'views:search' %}?keywords={{keywords}}&page={{next_page}}&limit={{limit}}" class="right">&gt;&gt;</a>
        </div>
    {% else %}
        <p>No images are found by query.</p>
    {% endif %}
</div>

views/templates/views/show.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'views/style.css' %}">

{% include "views/menu.html" %}

<div class="show">
    <h1>{{ image.title }}</h1>
    <div class="image">
        <a href="{{ MEDIA_URL }}{{ image.filename }}">
            <img src="{{ MEDIA_URL }}{{ image.filename }}" />
        </a>
    </div>
    <p>
        {% for word in keywords %}
            <a href="{% url 'views:search' %}?keywords={{word}}">{{ word }}</a>
        {% endfor %}
    </p>
    <p>{{ image.description }}</p>
    <p>Posted: {{ image.pub_date }}</p>
    <p>
        <a href="{% url 'views:update' pk=image.id %}">&#x1f58a;&#xfe0f;</a>
    </p>
</div>

views/templates/views/submit.html
{% load static %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="{% static 'views/style.css' %}">

<script>
    $( function() {
        var availableTags = [
        {% for word in suggested_keywords %}
            "{{ word }}",
        {% endfor %}
        ];
        function split( val ) {
          return val.split( /,\s*/ );
        }
        function extractLast( term ) {
          return split( term ).pop();
        }

        $( "#keywords" )
        // don't navigate away from the field on tab when selecting an item
        .on( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).autocomplete( "instance" ).menu.active ) {
            event.preventDefault();
        }
        })
        .autocomplete({
            minLength: 0,
            source: function( request, response ) {
                // delegate back to autocomplete, but extract the last term
                response( $.ui.autocomplete.filter(
                availableTags, extractLast( request.term ) ) );
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function( event, ui ) {
                var terms = split( this.value );
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push( ui.item.value );
                // add placeholder to get the comma-and-space at the end
                terms.push( "" );
                this.value = terms.join( ", " );
                return false;
            }
        });
    });
</script>

{% include "views/menu.html" %}

<div class="submit">
    <h1>Submit new image</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form autocomplete="off" action="{% url 'views:submit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div id="dropZone" class="drop-zone"></div>
        <input type="file" id="image_upload" name="image_image" required="true" /><br />
        <input type="text" name="image_title" placeholder="title" required="true" /><br />
        <textarea name="image_description" placeholder="description" rows="3" cols="60" required="true"></textarea><br />
        <input type="text" id="keywords" name="image_keywords" placeholder="keywords" required="true" /><br />
        <input type="submit" value="Submit">
    </form>
</div>

<div class="loading hidden"></div>

<script type="text/javascript">
    var dropZone = document.getElementById('dropZone');

    // Optional.   Show the copy icon when dragging over.  Seems to only work for chrome.
    dropZone.addEventListener('dragover', function(e) {
        e.stopPropagation();
        e.preventDefault();
        e.dataTransfer.dropEffect = 'copy';
    });

    // Get file data on drop
    dropZone.addEventListener('drop', function(e) {
        e.stopPropagation();
        e.preventDefault();
        var files = e.dataTransfer.files; // Array of all files

        var loading = document.querySelector('.loading');
        loading.classList.remove("hidden");
        for (var i=0, file; file=files[i]; i++) {
            if (file.type.match(/image.*/)) {
                var reader = new FileReader();

                reader.onload = function(e2) {
                    let fileInput = document.querySelector('#image_upload');
                    fileInput.files = e.dataTransfer.files;
                    // finished reading file data.

                    let zone = document.querySelector('.drop-zone');
                    var img = document.createElement('img');
                    img.src= e2.target.result;
                    img.classList.add("uploaded-image");
                    zone.parentNode.insertBefore(img, zone);

                    var br = document.createElement('br');
                    zone.parentNode.insertBefore(br, zone);

                    loading.classList.add("hidden");
                }

                reader.readAsDataURL(file); // start reading the file data.
            }
        }
    });
</script>